apiVersion: v1
kind: ConfigMap
metadata:
  name: kotsadm-web-scripts
data:
  start-kotsadm-web.sh: |
    #!/bin/bash
    sed -i 's/###_REST_ENDPOINT_###/https:\/\/{{repl ConfigOption "hostname"}}\/api/v1g' /usr/share/nginx/html/index.html

    nginx -g "daemon off;"
