apiVersion: v1
kind: Service
metadata:
  name: kotsadm-api
  labels:
    app: kotsadm-api
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: http
  selector:
    app: kotsadm-api
