bases:
  - ../../base
  - ../../../web/kustomize/overlays/dev
  - ../../../api/kustomize/overlays/dev
  - ./minio
  - ../../../migrations/kustomize/overlays/dev

resources:
  - ./nodeport.yaml

patches:
  - ./deployment.yaml

